version: '3.7'

services:
  web:
    image: my_app/web
    container_name: myapp_web
    environment:
      ANSIBLE_LOCAL_TEMP: /tmp
      ANSIBLE_REMOTE_TEMP: /tmp
      ANSIBLE_RETRY_FILES_ENABLED: 'False'
      ANSIBLE_ROLES_PATH: /ansible-common/roles
    networks:
      - web
    volumes:
      - ./.data/nginx/sites-available:/etc/nginx/sites-available:ro
      - ./.data/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./.data/public:/public:ro
      - ./.data/var/log/nginx:/var/log/nginx
      - ./.data/var/run:/usr/local/var/run
      - /etc/letsencrypt:/etc/ssl:ro
    ports:
      - "80:80"
      - "443:443"
